DROP TABLE GIOCATORE;
CREATE TABLE GIOCATORE (
    ID_giocatore int not null AUTO_INCREMENT PRIMARY KEY,
    Nome varchar(255) NOT NULL,
    Cognome varchar(255),
    Squadra varchar(255),
    id_capitano int
);

INSERT INTO GIOCATORE(NOME,COGNOME,SQUADRA,ID_CAPITANO) VALUES("JUAN","CUADRADO","JUVENTUS",0);
INSERT INTO GIOCATORE(NOME,COGNOME,SQUADRA,ID_CAPITANO) VALUES("GIORGIO","CHIELLINI","JUVENTUS",1);
INSERT INTO GIOCATORE(NOME,COGNOME,SQUADRA,ID_CAPITANO) VALUES("LEONARDO","BONUCCI","JUVENTUS",0);
INSERT INTO GIOCATORE(NOME,COGNOME,SQUADRA,ID_CAPITANO) VALUES("MATTIA","DE SCIGLIO","JUVENTUS",1);


SELECT G1.NOME, G1.COGNOME,G2.COGNOME AS "Capitano" FROM GIOCATORE G1, GIOCATORE G2
WHERE G1.ID_CAPITANO = G2.ID_GIOCATORE;